name: push-to-docker-hub-azure

on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: aruckner
          password: ${{ secrets.dockerhub_password }}
          logout: true
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/aruckner/sdc_uebung4:${{ github.sha }}
          file: ./Dockerfile
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: ds20m002-hello
          # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
          publish-profile: ${{ secrets.publish_profile }}
          # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
          images: index.docker.io/aruckner/sdc_uebung4:${{ github.sha }}
